export { ReactComponent as ArrowIcon } from './arrow.svg'
export { ReactComponent as ArrowButton } from './arrowButton.svg'
export { ReactComponent as Logo } from './Logo.svg'
export { ReactComponent as Waves } from './wavesOpacity.svg'
export { ReactComponent as Close } from './close.svg'
